TEMPLATE: Add template and usage
ForgeLua/ForgeCMS pull request #3
Opened 2024-05-24 13:41 UTC by alexis-piquet

2024-05-27 13:51 UTC, iThorgrim requested changes
Change storybook/index.etlua to storybook/button.etlua

2024-05-28 06:51 UTC, alexis-piquet commented
> Change storybook/index.etlua to storybook/button.etlua

I'll create a dedicated PR to improve the storybook. Could you review this one and merge it if all flags are green? 🙏🏽

2024-05-28 10:01 UTC, iThorgrim commented
> Change storybook/index.etlua to storybook/button.etlua

Nice !

2024-05-28 10:01 UTC, iThorgrim approved these changes

2024-05-28 10:01 UTC, merged